name: Self-Hosted Runner Test

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  test-runner:
    runs-on: mac-machine  # Must match your runner label
    steps:
      - name: Print hostname
        run: hostname

      - name: Say Hello
        run: echo "✅ Self-hosted runner is working!"

      - name: Start Job
        run: |
          echo "Simulating a long-running task (sleeping 60s)..."
          sleep 60
          echo "✅ Job completed!"